# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5123
GET http://{{hostname}}:{{port}}/Start/Index
###
GET http://{{hostname}}:{{port}}/Start/One
###
GET http://{{hostname}}:{{port}}/Start/Two
###
GET http://{{hostname}}:{{port}}/Start/Three
###
POST http://{{hostname}}:{{port}}/Start/Index
###
POST http://{{hostname}}:{{port}}/Start/One
###
POST http://{{hostname}}:{{port}}/Start/Two
###
POST http://{{hostname}}:{{port}}/Start/Three


###
GET https://www.belstu.by/ HTTP/1.1
###
GET http://{{hostname}}:{{port}}/404/Test HTTP/1.1